const TOKEN_TYPE = {
  ADMIN: 'admin',
  CUSTOMER: 'customer',
};

const ORDER_STATUS = {
  PENDING: 'pending',
  PAID: 'paid',
  SHIPPED: 'shipped',
  DELIVERED: 'delivered',
  CANCELLED: 'cancelled',
};

const PAID_ORDER_STATUSES = [ORDER_STATUS.PAID, ORDER_STATUS.SHIPPED, ORDER_STATUS.DELIVERED];
const ACTIVE_ORDER_STATUSES = [ORDER_STATUS.PENDING, ORDER_STATUS.PAID, ORDER_STATUS.SHIPPED];

const ADMIN_ORDER_QUEUE_STATUS = {
  FULFILLED: 'FULFILLED',
  PENDING: 'PENDING',
};

const STOCK_STATUS = {
  CRITICAL: 'CRITICAL',
  LOW: 'LOW',
  OPTIMAL: 'OPTIMAL',
};

const STOCK_THRESHOLD = {
  CRITICAL: 5,
  LOW: 20,
};

const PAGINATION = {
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
};

module.exports = {
  TOKEN_TYPE,
  ORDER_STATUS,
  PAID_ORDER_STATUSES,
  ACTIVE_ORDER_STATUSES,
  ADMIN_ORDER_QUEUE_STATUS,
  STOCK_STATUS,
  STOCK_THRESHOLD,
  PAGINATION,
};
